import { Building2, CheckCircle2 } from "lucide-react";
import type { PaymentReceipt } from "@/lib/receipts";

function formatRM(amount: number) {
  return `RM ${amount.toLocaleString()}`;
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-MY", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatMonth(dateStr: string) {
  return new Intl.DateTimeFormat("en-MY", {
    month: "long",
    year: "numeric",
  }).format(new Date(`${dateStr}T00:00:00`));
}

export default function ReceiptDocument({ receipt }: { receipt: PaymentReceipt }) {
  return (
    <article className="overflow-hidden rounded-lg border border-border bg-card shadow-sm print:rounded-none print:border-0 print:shadow-none">
      <header className="flex flex-col gap-6 border-b border-border p-6 sm:flex-row sm:items-start sm:justify-between print:p-0 print:pb-6">
        <div className="flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <Building2 className="h-5 w-5" />
          </div>
          <div>
            <p className="text-lg font-bold text-foreground">RentFlow</p>
            <p className="text-xs text-muted-foreground">Official rent payment receipt</p>
          </div>
        </div>
        <div className="text-left sm:text-right">
          <p className="text-xs font-semibold uppercase text-muted-foreground">Receipt</p>
          <p className="text-xl font-bold text-foreground">{receipt.receiptNumber}</p>
          <p className="mt-1 text-xs text-muted-foreground">Issued {formatDate(receipt.paidOn)}</p>
        </div>
      </header>

      <section className="grid gap-6 p-6 sm:grid-cols-2 print:p-0 print:pt-6">
        <div className="space-y-1">
          <p className="text-xs font-semibold uppercase text-muted-foreground">Received From</p>
          <p className="text-base font-semibold text-foreground">{receipt.tenantName}</p>
          <p className="text-sm text-muted-foreground">
            {receipt.propertyName} · Unit {receipt.unitNumber}
          </p>
        </div>
        <div className="space-y-1 sm:text-right">
          <p className="text-xs font-semibold uppercase text-muted-foreground">Payment Status</p>
          <p className="inline-flex items-center gap-1.5 rounded-full border border-green-200 bg-green-50 px-2.5 py-1 text-xs font-semibold text-green-700">
            <CheckCircle2 className="h-3.5 w-3.5" />
            Paid
          </p>
          <p className="text-sm text-muted-foreground">Method: {receipt.method}</p>
        </div>
      </section>

      <section className="px-6 pb-6 print:px-0">
        <div className="overflow-hidden rounded-lg border border-border print:rounded-none">
          <div className="grid grid-cols-[1fr_auto] border-b border-border bg-muted/40 px-4 py-3 text-sm font-semibold text-foreground">
            <span>Description</span>
            <span className="text-right">Amount</span>
          </div>
          <div className="grid grid-cols-[1fr_auto] gap-4 px-4 py-4 text-sm">
            <div>
              <p className="font-medium text-foreground">
                Monthly rent · {formatMonth(receipt.monthStart)}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                Due {formatDate(receipt.dueDate)} · Paid {formatDate(receipt.paidOn)}
              </p>
            </div>
            <p className="font-semibold text-foreground">{formatRM(receipt.amount)}</p>
          </div>
          <div className="grid grid-cols-[1fr_auto] border-t border-border bg-muted/30 px-4 py-3 text-sm">
            <span className="font-semibold text-foreground">Total Paid</span>
            <span className="text-lg font-bold text-foreground">{formatRM(receipt.amount)}</span>
          </div>
        </div>
      </section>

      <footer className="border-t border-border px-6 py-4 text-xs text-muted-foreground print:px-0">
        This receipt was generated by RentFlow for a dummy MVP payment. No real payment gateway
        charge is represented by this demo transaction.
      </footer>
    </article>
  );
}
